---
root: true

extends:
  - standard # https://github.com/standard/eslint-config-standard#readme
  - prettier # https://github.com/prettier/eslint-config-prettier#readme
  - next/core-web-vitals
  - plugin:storybook/recommended

rules:
  # ESLint default rules > https://eslint.org/docs/latest/rules
  indent: ["error", 2, { "SwitchCase": 1 }]
  quotes: ["error", "double"]
  semi: ["error", "always"]
  comma-dangle: ["error", "always-multiline"]
  eol-last: ["error", "always"]
  template-curly-spacing: "off" # > control by Prettier

  # Standard Rules > https://standardjs.com/rules.html#rules
  space-before-function-paren: "off"
